In [1]:
print('Hello, World!')

Hello, World!


In [2]:
d = {'k1': 1, 5: 2}

In [3]:
d[5]

2

In [4]:
import numpy as np

In [12]:
vals = np.array([[3, 4, 1.], [7, 5, 9.], [2, 3, 5], [4, 4, 5]])

In [11]:
avgs = np.nanmean(vals, axis=0)
avgs

array([4., 4., 5.])

In [14]:
def pnp(vals_slice, avg):
    return vals_slice / avg

In [16]:
pnp(vals[:,0], avgs[0])

array([0.75, 1.75, 0.5 , 1.  ])

In [17]:
np.transpose(avgs)

array([4., 4., 5.])

In [21]:
tavgs = np.reshape(avgs, (1, avgs.size))
print('array: {ary}'.format(ary=tavgs))
print('shape: {shape}'.format(shape=tavgs.shape))

array: [[4. 4. 5.]]
shape: (1, 3)


In [22]:
vals / tavgs

array([[0.75, 1.  , 0.2 ],
       [1.75, 1.25, 1.8 ],
       [0.5 , 0.75, 1.  ],
       [1.  , 1.  , 1.  ]])